name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Criar os arquivos `app.key` e `app.pub` a partir dos secrets
      - name: Create app.key and app.pub
        run: |
          echo "${{ secrets.APP_KEY }}" > src/main/resources/app.key
          echo "${{ secrets.APP_PUB }}" > src/main/resources/app.pub

      # Buildar o projeto com Maven, utilizando os arquivos criados
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: marcosduarte-dev/correlato-back
          tags: latest
          registry: c.tsapp.dev
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}